// src/services/pdf.js — PDF Generation Service
// Uses pdfkit (installed) to generate:
//   1. Lease agreement PDFs
//   2. Monthly estate manager owner reports
//
// Note: pdfkit streams to a Buffer — no temp files needed

'use strict';
const PDFDocument = require('pdfkit');
const logger = require('./logger');

// ── Helpers ─────────────────────────────────────────────────

function fmtNaira(n) {
  if (!n) return '₦0';
  return '₦' + parseFloat(n).toLocaleString('en-NG', { minimumFractionDigits: 0 });
}

function bufferize(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}

function header(doc, title, subtitle) {
  doc.rect(0, 0, doc.page.width, 70).fill('#0B1220');
  doc.fontSize(18).fillColor('#FFFFFF').font('Helvetica-Bold')
     .text('PROPATI', 50, 22);
  doc.fontSize(8).fillColor('#C9952A').font('Helvetica')
     .text('NIGERIA\'S VERIFIED PROPERTY PLATFORM', 50, 44);
  doc.fontSize(10).fillColor('#AAAAAA').font('Helvetica')
     .text(title, 300, 22, { width: 260, align: 'right' });
  if (subtitle) {
    doc.fontSize(8).fillColor('#888888')
       .text(subtitle, 300, 36, { width: 260, align: 'right' });
  }
  doc.fillColor('#000000');
  return doc.y = 90;
}

function sectionTitle(doc, text) {
  doc.moveDown(0.5);
  doc.rect(50, doc.y, doc.page.width - 100, 22).fill('#0B1220');
  doc.fontSize(9).fillColor('#FFFFFF').font('Helvetica-Bold')
     .text(text.toUpperCase(), 58, doc.y - 16);
  doc.fillColor('#000000');
  doc.moveDown(0.3);
}

function row(doc, label, value, yOverride) {
  const y = yOverride !== undefined ? yOverride : doc.y;
  doc.fontSize(9).fillColor('#555555').font('Helvetica')
     .text(label + ':', 50, y, { width: 180, continued: false });
  doc.fontSize(9).fillColor('#111111').font('Helvetica-Bold')
     .text(String(value), 240, y, { width: 310 });
  doc.y = y + 18;
}

function kpiBox(doc, x, y, w, h, label, value, color) {
  doc.rect(x, y, w, h).stroke('#DDDDDD');
  doc.rect(x, y, 4, h).fill(color || '#0B1220');
  doc.fontSize(18).fillColor(color || '#0B1220').font('Helvetica-Bold')
     .text(value, x + 12, y + 8, { width: w - 20 });
  doc.fontSize(8).fillColor('#777777').font('Helvetica')
     .text(label, x + 12, y + 34, { width: w - 20 });
}

// ── LEASE AGREEMENT PDF ─────────────────────────────────────
async function generateLeasePDF(data) {
  // data: { agreement, listing, landlord, tenant, agent }
  const { agreement: agr, listing, landlord, tenant } = data;

  const doc = new PDFDocument({ size: 'A4', margins: { top: 90, bottom: 60, left: 50, right: 50 } });
  const p = bufferize(doc);

  header(doc, 'TENANCY AGREEMENT', `Ref: ${agr.id}`);

  doc.fontSize(14).fillColor('#111111').font('Helvetica-Bold')
     .text('RESIDENTIAL TENANCY AGREEMENT', { align: 'center' });
  doc.fontSize(9).fillColor('#777777').font('Helvetica')
     .text(`Generated by PROPATI on ${new Date().toLocaleDateString('en-NG', { day:'numeric', month:'long', year:'numeric' })}`, { align: 'center' });
  doc.moveDown(1);

  sectionTitle(doc, '1. Parties');
  row(doc, 'Landlord', `${landlord.full_name} (${landlord.email})`);
  row(doc, 'Tenant', `${tenant.full_name} (${tenant.email})`);
  if (tenant.phone) row(doc, 'Tenant Phone', tenant.phone);

  sectionTitle(doc, '2. Property');
  row(doc, 'Property', listing.title);
  row(doc, 'Address', listing.address + ', ' + listing.area);
  if (listing.bedrooms)  row(doc, 'Bedrooms', listing.bedrooms);
  if (listing.bathrooms) row(doc, 'Bathrooms', listing.bathrooms);
  if (listing.size_sqm)  row(doc, 'Size', listing.size_sqm + ' m²');

  sectionTitle(doc, '3. Terms & Payment');
  row(doc, 'Agreement Type', agr.type.replace('_',' ').toUpperCase());
  row(doc, 'Start Date', new Date(agr.start_date).toLocaleDateString('en-NG', { day:'numeric', month:'long', year:'numeric' }));
  if (agr.end_date) row(doc, 'End Date', new Date(agr.end_date).toLocaleDateString('en-NG', { day:'numeric', month:'long', year:'numeric' }));
  row(doc, 'Rent Amount', fmtNaira(agr.rent_amount) + ' per ' + (agr.rent_period || 'year'));
  if (agr.caution_deposit) row(doc, 'Caution Deposit', fmtNaira(agr.caution_deposit));
  if (agr.service_charge)  row(doc, 'Service Charge', fmtNaira(agr.service_charge));
  row(doc, 'Notice Period', (agr.notice_period_days || 30) + ' days');

  sectionTitle(doc, '4. Standard Conditions');
  const clauses = [
    'The Tenant shall use the property solely for residential purposes.',
    'The Tenant shall maintain the property in good condition and report damages immediately.',
    'The Tenant shall not sub-let any part of the property without written consent from the Landlord.',
    'The Landlord shall maintain the structural integrity of the property and ensure essential services are functional.',
    'Disputes arising from this agreement shall be mediated through the PROPATI Dispute Resolution system.',
    'This agreement is legally binding upon both parties under Nigerian law.',
  ];
  clauses.forEach((c, i) => {
    doc.fontSize(9).fillColor('#333333').font('Helvetica')
       .text(`${i + 1}. ${c}`, 50, doc.y, { width: doc.page.width - 100 });
    doc.moveDown(0.3);
  });

  if (agr.special_clauses) {
    sectionTitle(doc, '5. Special Conditions');
    doc.fontSize(9).fillColor('#333333').font('Helvetica')
       .text(agr.special_clauses, 50, doc.y, { width: doc.page.width - 100 });
  }

  sectionTitle(doc, '6. Signatures');
  doc.moveDown(0.5);

  // Signature boxes
  const sigY = doc.y;
  doc.rect(50, sigY, 220, 60).stroke('#CCCCCC');
  doc.rect(330, sigY, 220, 60).stroke('#CCCCCC');

  doc.fontSize(9).fillColor('#555555').font('Helvetica')
     .text('LANDLORD SIGNATURE', 60, sigY + 5);
  doc.fontSize(8).fillColor('#333333').font('Helvetica-Bold')
     .text(landlord.full_name, 60, sigY + 20);
  if (agr.landlord_signed_at) {
    doc.fontSize(7).fillColor('#2AAD72')
       .text('✓ Signed electronically: ' + new Date(agr.landlord_signed_at).toLocaleString('en-NG'), 60, sigY + 36);
    doc.fontSize(7).fillColor('#999999')
       .text('IP: ' + (agr.landlord_ip || 'recorded'), 60, sigY + 48);
  } else {
    doc.fontSize(8).fillColor('#EF4444').text('Awaiting signature', 60, sigY + 36);
  }

  doc.fontSize(9).fillColor('#555555').font('Helvetica')
     .text('TENANT SIGNATURE', 340, sigY + 5);
  doc.fontSize(8).fillColor('#333333').font('Helvetica-Bold')
     .text(tenant.full_name, 340, sigY + 20);
  if (agr.tenant_signed_at) {
    doc.fontSize(7).fillColor('#2AAD72')
       .text('✓ Signed electronically: ' + new Date(agr.tenant_signed_at).toLocaleString('en-NG'), 340, sigY + 36);
    doc.fontSize(7).fillColor('#999999')
       .text('IP: ' + (agr.tenant_ip || 'recorded'), 340, sigY + 48);
  } else {
    doc.fontSize(8).fillColor('#EF4444').text('Awaiting signature', 340, sigY + 36);
  }

  // Footer
  doc.y = sigY + 75;
  doc.fontSize(7).fillColor('#AAAAAA').font('Helvetica')
     .text(
       `This agreement was created through PROPATI (propati.ng). Agreement ID: ${agr.id}. ` +
       `Both parties confirm they have read and understood all terms. ` +
       `Electronic signatures are valid under Nigerian law (NITDA Guidelines on Electronic Transactions).`,
       50, doc.y, { width: doc.page.width - 100, align: 'center' }
     );

  doc.end();
  return p;
}

// ── MONTHLY OWNER REPORT PDF ────────────────────────────────
async function generateMonthlyReport(data) {
  const {
    org, month,
    totalUnits, occupied,
    collected, overdue, totalDue,
    paidCount, overdueCount,
    ticketStats,
  } = data;

  const [year, mo] = month.split('-');
  const monthName = new Date(parseInt(year), parseInt(mo) - 1, 1)
    .toLocaleDateString('en-NG', { month: 'long', year: 'numeric' });

  const doc = new PDFDocument({ size: 'A4', margins: { top: 90, bottom: 60, left: 50, right: 50 } });
  const p = bufferize(doc);

  header(doc, `${org.name}`, `Monthly Report — ${monthName}`);

  doc.fontSize(14).fillColor('#0B1220').font('Helvetica-Bold')
     .text('Monthly Portfolio Report', { align: 'center' });
  doc.fontSize(10).fillColor('#555555').font('Helvetica')
     .text(monthName, { align: 'center' });
  doc.moveDown(0.5);

  // Generated info
  doc.fontSize(8).fillColor('#999999').font('Helvetica')
     .text(`Generated: ${new Date().toLocaleDateString('en-NG', { day:'numeric', month:'long', year:'numeric', hour:'2-digit', minute:'2-digit' })} · ${org.plan_tier?.toUpperCase()} Plan`, { align: 'center' });
  doc.moveDown(1);

  // KPI boxes
  const kpiW = 120;
  const kpiH = 55;
  const kpiY = doc.y;
  kpiBox(doc, 50,  kpiY, kpiW, kpiH, 'TOTAL UNITS', totalUnits,           '#0B1220');
  kpiBox(doc, 180, kpiY, kpiW, kpiH, 'OCCUPANCY',   occupied + '/' + totalUnits + ' (' + (totalUnits ? Math.round(occupied/totalUnits*100) : 0) + '%)', '#2AAD72');
  kpiBox(doc, 310, kpiY, kpiW, kpiH, 'RENT COLLECTED', fmtNaira(collected), '#C9952A');
  kpiBox(doc, 440, kpiY, kpiW, kpiH, 'ARREARS',    fmtNaira(overdue),     '#EF4444');
  doc.y = kpiY + kpiH + 20;

  sectionTitle(doc, 'Rent Collection Summary');
  row(doc, 'Total Expected',    fmtNaira(totalDue));
  row(doc, 'Collected',         fmtNaira(collected) + (paidCount ? ` (${paidCount} payments)` : ''));
  row(doc, 'Outstanding',       fmtNaira(totalDue - collected));
  row(doc, 'Overdue Payments',  overdueCount > 0 ? `${overdueCount} units — ${fmtNaira(overdue)}` : 'None ✓');
  row(doc, 'Collection Rate',   totalDue > 0 ? Math.round(collected / totalDue * 100) + '%' : 'N/A');

  sectionTitle(doc, 'Portfolio Status');
  row(doc, 'Total Managed Units', totalUnits);
  row(doc, 'Occupied',            occupied);
  row(doc, 'Vacant',              totalUnits - occupied);
  row(doc, 'Occupancy Rate',      totalUnits ? Math.round(occupied / totalUnits * 100) + '%' : 'N/A');

  if (ticketStats && ticketStats.length > 0) {
    sectionTitle(doc, 'Maintenance Activity');
    ticketStats.forEach(t => {
      row(doc, t.status.replace('_', ' ').charAt(0).toUpperCase() + t.status.slice(1), t.count + ' tickets');
    });
  }

  // Footer
  doc.moveDown(2);
  doc.rect(50, doc.y, doc.page.width - 100, 1).fill('#CCCCCC');
  doc.moveDown(0.5);
  doc.fontSize(7).fillColor('#AAAAAA').font('Helvetica')
     .text(
       `This report was auto-generated by PROPATI for Business (propati.ng) for ${org.name}. ` +
       `Report Period: ${monthName}. All figures are subject to final reconciliation. ` +
       `For queries contact support@propati.ng.`,
       50, doc.y, { width: doc.page.width - 100, align: 'center' }
     );

  doc.end();
  return p;
}

module.exports = { generateLeasePDF, generateMonthlyReport };
